import { Folder, Vocabulary } from '@/types';

export const INITIAL_FOLDERS: Folder[] = [
  {
    id: 'f-env',
    name: 'Environment',
    parentId: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f-climate',
    name: 'Climate Change',
    parentId: 'f-env',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f-fin',
    name: 'Finance',
    parentId: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f-banking',
    name: 'Banking',
    parentId: 'f-fin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f-edu',
    name: 'Education',
    parentId: null,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'f-research',
    name: 'Research',
    parentId: 'f-edu',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_VOCABULARIES: Vocabulary[] = [
  {
    id: 'v-1',
    folderId: 'f-climate',
    word: 'Mitigate',
    meaning: 'Giảm thiểu, làm dịu bớt',
    wordType: 'verb',
    phonetic: '/ˈmɪt.ɪ.ɡeɪt/',
    level: 'Band 7.5',
    example: 'Governments must mitigate climate change impacts through sustainable policies.',
    status: 'learning',
    nextReviewAt: new Date().toISOString(),
    intervalDays: 1,
    repetitions: 1,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-2',
    folderId: 'f-climate',
    word: 'Deteriorate',
    meaning: 'Mất phẩm chất, xấu đi',
    wordType: 'verb',
    phonetic: '/dɪˈtɪə.ri.ə.reɪt/',
    level: 'Band 7.0',
    example: 'Air quality continues to deteriorate rapidly in heavily industrialized urban areas.',
    status: 'new',
    nextReviewAt: new Date().toISOString(),
    intervalDays: 0,
    repetitions: 0,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-3',
    folderId: 'f-climate',
    word: 'Biodiversity',
    meaning: 'Đa dạng sinh học',
    wordType: 'noun',
    phonetic: '/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/',
    level: 'Band 7.0',
    example: 'Deforestation causes severe loss of biodiversity in tropical rainforests.',
    status: 'mastered',
    nextReviewAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    intervalDays: 7,
    repetitions: 3,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-4',
    folderId: 'f-banking',
    word: 'Cumbersome',
    meaning: 'Cồng kềnh, phức tạp',
    wordType: 'adjective',
    phonetic: '/ˈkʌm.bə.səm/',
    level: 'Band 8.0',
    example: 'Traditional banking procedures are often cumbersome compared to modern fintech apps.',
    status: 'learning',
    nextReviewAt: new Date().toISOString(),
    intervalDays: 3,
    repetitions: 2,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-5',
    folderId: 'f-banking',
    word: 'Allocate',
    meaning: 'Phân bổ, chỉ định',
    wordType: 'verb',
    phonetic: '/ˈæl.ə.keɪt/',
    level: 'Band 7.5',
    example: 'The central bank decided to allocate funds for green energy development projects.',
    status: 'new',
    nextReviewAt: new Date().toISOString(),
    intervalDays: 0,
    repetitions: 0,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-6',
    folderId: 'f-research',
    word: 'Empirical',
    meaning: 'Dựa trên thực nghiệm',
    wordType: 'adjective',
    phonetic: '/ɪmˈpɪr.ɪ.kəl/',
    level: 'Band 8.0',
    example: 'Researchers must provide empirical evidence to support their scientific claims.',
    status: 'new',
    nextReviewAt: new Date().toISOString(),
    intervalDays: 0,
    repetitions: 0,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-7',
    folderId: 'f-research',
    word: 'Hypothesis',
    meaning: 'Giả thuyết',
    wordType: 'noun',
    phonetic: '/haɪˈpɒθ.ə.sɪs/',
    level: 'Band 7.0',
    example: 'The initial hypothesis was confirmed after multiple rounds of lab testing.',
    status: 'mastered',
    nextReviewAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    intervalDays: 7,
    repetitions: 3,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v-8',
    folderId: 'f-research',
    word: 'Synthesize',
    meaning: 'Tổng hợp',
    wordType: 'verb',
    phonetic: '/ˈsɪn.θə.saɪz/',
    level: 'Band 7.5',
    example: 'Students need to synthesize information from various academic publications.',
    status: 'learning',
    nextReviewAt: new Date().toISOString(),
    intervalDays: 1,
    repetitions: 1,
    easeFactor: 2.5,
    createdAt: new Date().toISOString(),
  },
];
